<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>  

<footer class="footer">
  <div class="footer-lists">
    <div class="container">
      <div class="row">
        
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
          <ul>
          <li><h4>界面设计师UI</h4></li>
          <li><img src="res/img/developer/t2.png" alt="..." style="width:100%"/></li>
          <li>技术门槛不高，学点HTML和CSS就行，你看他俩累的…</li>
          </ul>
        </div>
        
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
          <ul>
          <li><h4>前端工程师FE</h4></li>
          <li><img src="res/img/developer/t3.png" alt="..." style="width:100%"/></li>
          <li>一会UI找我，一会后台找我，你俩能不能别来烦我…</li>
          </ul>
        </div>

        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
          <ul>
            <li><h4>后台工程师BE</h4></li>
            <li><img src="res/img/developer/t1.png" alt="..." style="width:100%"/></li>
            <li>又有bug，我好累，我好方！又能欣赏明天的日出了，好期待……</li>
          </ul>
        </div>
        
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
          <h4>站点介绍</h4>
          <p>没啥特长，就会吹牛 ！</p>
          <p>只要口才好，只要脸皮厚 !</p>
          <p>做产品推广比做产品研发舒服多了 !</p>
          <p>我陪甲方喝咖啡的时候，他们都在加班 !</p>
        </div>
        
      </div>
    </div>
  </div>
  
  <div class="footer-bottom">
    <p class="text-center">copyright &copy; 2000 - now by 
      <a href="tool/iconfont/demo.html" title="别问我是谁，点我试试！" target="_blank">GeekCN</a>
      <a title="庐山皇家科技学院">.JJU</a> 
    </p>
    <p class="text-center">mvcDemo 学习交流 &reg; 赣暗网未备也不敢备 0110 0110 0110 号</p>
  </div>

</footer>