<div class="content-wrapper">


  <!-- 2、统计块 -->
  <section class="content">
    <div class="container-fluid">
      <!-- 统计块 -->
      <div class="row">
        <div class="col-lg-3 col-6">
          <!-- 1 -->
          <div class="small-box bg-info">
            <div class="inner">
              <p>学生数</p>
              <h3 id="student_number">0</h3>
            </div>
            <div class="icon">
              <i class="icon-users6"></i>
            </div>
            <a id="a_student" href="javascript:void(0);" class="small-box-footer">查看详情&ensp;<i class="fas fa-arrow-circle-right"></i></a>
          </div>
        </div><!-- ./col -->

        <div class="col-lg-3 col-6">
          <!-- 2 -->
          <div class="small-box bg-warning">
            <div class="inner">
              <p>教师数</p>
              <h3 id="teacher_number">0</h3>
            </div>
            <div class="icon">
              <i class="icon-bussinessman"></i>
            </div>
            <a id="a_teacher" href="javascript:void(0);" class="small-box-footer">查看详情&ensp;<i class="fas fa-arrow-circle-right"></i></a>
          </div>
        </div><!-- ./col -->

        <div class="col-lg-3 col-6">
          <!-- 3 -->
          <div class="small-box bg-success">
            <div class="inner">
              <p>课程数</p>
              <h3 id="course_number">0</h3>
            </div>
            <div class="icon">
              <i class="icon-clipboard4"></i>
            </div>
            <a id="a_course" href="javascript:void(0);" class="small-box-footer">查看详情&ensp;<i class="fas fa-arrow-circle-right"></i></a>
          </div>
        </div><!-- ./col -->

        <div class="col-lg-3 col-6">
          <!-- 4 -->
          <div class="small-box bg-danger">
            <div class="inner">
              <p>成绩记录</p>
              <h3 id="score_number">0</h3>
            </div>
            <div class="icon">
              <i class="icon-viewlist"></i>
            </div>
            <a id="a_score" href="javascript:void(0);" class="small-box-footer">查看详情&ensp;<i class="fas fa-arrow-circle-right"></i></a>
          </div>
        </div><!-- ./col -->
      </div><!-- /.container-fluid -->
    </div><!-- /.row -->
  </section><!-- /.content -->

  <!-- 3、其他统计数据 -->
  <section class="content">
    <table id="tbl_position" class="table table-bordered table-striped"></table>
  </section><!-- /.content -->

  <!-- 相关脚本 -->
  <script type="text/javascript" src="admin/homePage/homePage.js"></script>

</div>