<div class="content-wrapper" style="margin-top: 10px;">
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">
          <div class="card">

            <select id="select_course" class="form-control"></select>
            <div id="highchart_count" style="width:100%;margin-top: 40px;"></div>

          </div><!-- /.card -->
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </section><!-- /.content -->
</div><!-- /.content-wrapper -->


<!-- 表格相关脚本 -->
<script type="text/javascript" src="admin/score/count/count.js"></script>